---
region: 'eu-west-2'

account_id: "579878096224"

component: 'test'

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

infrastructure_events_bucket: "tobyclemson-open-source"
